### ISSUE TITLE
Font Letter Spacing and Line Height

### ISSUE THREAD

**Issue by abdullahtekin** [kus/php-image#13]
Will you do letter-spacing and line-height properties for text?

**Comment by kus** [comment]
Hi @abdullahtekin I just added the ability to change line-height with the last update, but don't see me adding in letter spacing any time soon. You can now change the line height with `->setLineHeight(1.5)`.

The problem with letter spacing is there is no easy way to add it in, you would need to make a `imageftbbox` for every single character.
