### ISSUE TITLE
Can't really center text

### ISSUE THREAD

**Issue by barisunver** [kus/php-image#14]
Hi. First off, great work! It's very easy to use yet it has a lot to offer.

I'm having some problems though. I tried to center a multiline text, but I can't do it. Here's my code:

```
$image = new PHPImage();
$image->setDimensionsFromImage( $post_image );
$image->draw( $post_image );
$image->resize( 1200, 630, true, true );
$image->draw( $overlay ); // the semi-transparent black box
$image->setAlignHorizontal( 'center' );
$image->setAlignVertical( 'center' );
$image->setFont( DIZIN . 'OpenSans-Light.ttf' );
$image->textBox(
	$post_content,
	array(
		'width' => 1100,
		'height' => 530,
		'fontSize' => 24,
		'x' => 600,
		'y' => 315
	)
);
$image->save( '/home/asd/public_html/i/' . md5( $post_id ) . '.jpg' );
```

This is the generated result:

![image](https://cloud.githubusercontent.com/assets/1160221/23482975/acbc5972-fed9-11e6-90f4-cd604be7a792.png)

In the example above, I figured that the origin point must be the center of the image (1200x630 > 600x315). But then I thought "maybe the origin point designates the top-left of the text box, and I should make a different calculation". So, I set the origin point to 50x50 (because the overlayed black box starts at 50x50) and set the width to 1100x530 again:

```
$image = new PHPImage();
$image->setDimensionsFromImage( $post_image );
$image->draw( $post_image );
$image->resize( 1200, 630, true, true );
$image->draw( $overlay );
$image->setAlignHorizontal( 'center' );
$image->setAlignVertical( 'center' );
$image->setFont( DIZIN . 'OpenSans-Light.ttf' );
$image->textBox(
	$post_content,
	array(
		'width' => 1100,
		'height' => 530,
		'fontSize' => 24,
		'x' => 50,
		'y' => 50
	)
);
$image->save( '/home/asd/public_html/i/' . md5( $post_id ) . '.jpg' );
```

Sadly, still no luck :( Here's the generated image:

![image](https://cloud.githubusercontent.com/assets/1160221/23483138/6504822a-feda-11e6-9965-5d1e9fcd34dc.png)

What am I missing here? How do I align the text box?

**Comment by osirismqz** [comment]
Same issue here.

Checking the code, it seems that "textBox" doens't have alignment parameters.

**Comment by DuyguC** [comment]
I faced the same issue too and modified the PHPImage.php file a little. Hope it helps to you too.

[PHPImage.zip](https://github.com/kus/php-image/files/1001115/PHPImage.zip)

**Comment by tdolph** [comment]
@DuyguC Thanks for sharing. But, i used it and i have both of these in textbox parameters but it does not work. Text is still left.

'alignHorizontal' => 'center',
'alignVertical' => 'center',

**Comment by om3** [comment]
Same issue. Did was solved?

**Comment by tdolph** [comment]
I guess no. This package is probably almost abandoned.

**Comment by kus** [comment]
Sorry for the lack of updates and communication. I stopped using PHP about 4 years ago, but I'm looking into this now for you and will have a fix in the next few hours as it is pretty requested.

Aligning text works with a single line using `text` but breaks when you have multiline text, but I'm halfway through a fix for you guys :)

**Comment by kus** [comment]
I have resolved this with the latest commit.

Please see https://github.com/kus/php-image/blob/master/test/center.php for an example which I tried to mimic what you were doing.

Here is examples of the output with different alignments:
![68747470733a2f2f7261772e6769746875622e636f6d2f6b75732f7068702d696d6167652f6d61737465722f746573742f6578616d706c65732f63656e7465722e6a7067](https://user-images.githubusercontent.com/571523/32001354-4b183b2e-b9e5-11e7-8a17-59d24e537cb5.jpg)

**Comment by tdolph** [comment]
Thank you very much! :)

**Comment by om3** [comment]
Thanks, nice job!

**Comment by barisunver** [comment]
Thank you, @kus !
