### ISSUE TITLE
Can't Change the bg color of $image->text(..) function

### ISSUE THREAD

**Issue by navt3k** [kus/php-image#15]
$image->text($text_one, array(
		'fontSize' => 16, // Desired starting font size
		'x' => 45,
		'y' => 25,
		'width' => 170,
		'height' => 30,
		'alignHorizontal' => 'center',
		'alignVertical' => 'center',
		'debug' => true
	));

is there any arguments to add to it to change bg color as it always gives cyan as bg color of text..

**Comment by kus** [comment]
Hi @navt3k you have `debug => true` set, change it to false or remove it and it will stop drawing the cyan bounding box. If you actually want to draw a different colour box behind your text you can manually draw it with `rectangle`. See this for an example https://github.com/kus/php-image/blob/master/test/center.php
