### ISSUE TITLE
Increase width.

### ISSUE THREAD

**Issue by om3** [kus/php-image#16]
Hi @kus , I can't increase the width of image. It width 900px and I need to expand to 1200px. I get max 900px. 
How to force 1200px?

`      $bg = 'uimages/78-7965ce34b606eb1ed5a14e0764a325cb.png';

      $overlay = 'imgs/balloonShareCapa.png';

      $image = new PHPImage();
      $image->setDimensionsFromImage($overlay);
      $image->draw($bg);
      $image->draw($overlay, '50%', '75%');
      $image->rectangle(40, 40, 120, 80, array(0, 0, 0), 0.5);
      $image->setFont('LiberationMono-Regular.ttf');
      $image->setTextColor(array(255, 255, 255));
      $image->setStrokeWidth(1);
      $image->setStrokeColor(array(0, 0, 0));
      $image->text('Hello World!', array('fontSize' => 12, 'x' => 50, 'y' => 50));
      $image->text('This is a big sentence with width 200px', array(
          'fontSize' => 60,
          'x' => 300,
          'y' => 0,
          'width' => 200,
          'height' => 50,
          'alignHorizontal' => 'center',
          'alignVertical' => 'center',
          'debug' => true
      ));
      $image->text('This is a big sentence', array(
          'fontSize' => 60,
          'x' => 300,
          'y' => 200,
          'width' => 200,
          'height' => 50,
          'alignHorizontal' => 'center',
          'alignVertical' => 'center',
          'debug' => true
      ));
      $image->textBox('Lorem ipsum dolor sit amet, consectetur adipiscing elit.', array('width' => 100, 'fontSize' => 8, 'x' => 50, 'y' => 70));
      $image->rectangle(40, 140, 170, 160, array(0, 0, 0), 0.5);
      $image->textBox('Auto wrap and scale font size to multiline text box width and height bounds. Vestibulum venenatis risus scelerisque enim faucibus, ac pretium massa condimentum. Curabitur faucibus mi at convallis viverra. Integer nec finibus ligula, id hendrerit felis.', array(
          'width' => 150,
          'height' => 140,
          'fontSize' => 16,
          'x' => 50,
          'y' => 150
      ));
      $image->show();`

**Comment by kus** [comment]
Hi @om3 

You are looking for the [4th parameter of `resize` (upscale=true)](https://github.com/kus/php-image/blob/master/src/PHPImage.php#L480).

I made an example for you https://github.com/kus/php-image/blob/master/test/upscale.php
