### ISSUE TITLE
StrokeWidth / StrokeColor not working in array.

### ISSUE THREAD

**Issue by choice2rejoice** [kus/php-image#17]
At first, a really big thank you for this script!
Question,
Why is  "stroke"  not working when it is set in an array? When I look at the script, the stroke option seems to be an option that you set like the width and height, IN the array. Can you please tell me why next script is not working, but the one beneath it does?

With kind regards,
Koert

NOT working:
        $image->textBox('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie tortor quam, at congue nibh imperdiet dapibus.', array(
		'width' => 150,
		'height' => 140,
		'fontSize' => 16, // Desired starting font size
		'x' => 50,
		'y' => 150,
                'strokeWidth' => $image->setStrokeWidth(1),
                'strokeColor' => $image->setStrokeColor(array( 55, 189, 102))
	));

WORKING:
        $image->setStrokeWidth(1);
	$image->setStrokeColor(array(0, 0, 0));
	$image->textBox('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam molestie tortor quam, at congue nibh imperdiet dapibus.', array(
		'width' => 100,
		'height' => 100,
		'fontSize' => 16, // Desired starting font size
		'x' => 50,
		'y' => 200
	));

After I put the option in   I get the next messages: 

Notice: Object of class PHPImage could not be converted to int in D:\wamp64\www\php-image-master\src\PHPImage.php on line 971
Fatal error: Cannot use object of type PHPImage as array in D:\wamp64\www\php-image-master\src\PHPImage.php on line 972

EDIT:  I used the next in the array and that's working. 
        'strokeWidth' => 1,
	'strokeColor' => array( 55, 189, 102),

**Comment by kus** [comment]
Hi @choice2rejoice 

You must assign it like this:

```
'strokeWidth' => 1,
'strokeColor' => array(255, 0, 0)
```

I created a an example with both methods for you to look at https://github.com/kus/php-image/blob/master/test/stroke.php

Also; thanks for bringing stroke to my attention, there was actually a bug on multiline stroking which I have fixed 😄

**Comment by choice2rejoice** [comment]
YES!!! And I was scared it was a stupid question :-P
Thanks for your response and again, thanks for your script!
