### ISSUE TITLE
textBox with Fontsize scaling

### ISSUE THREAD

**Issue by rufinus** [kus/php-image#3]
Is there any way to compine the fontsize scaling from text() to use in textBox?

For example: 
I have a string with various length, should be displayed multiline within the borders of a specific area.
So i need wordwraping, and font scaling in one rush

TIA

**Comment by kus** [comment]
I've added support for `height` variable to `textBox`, if `height` is present it will now scale the font down to fit the multiline text into the bounds of the box.

See https://github.com/kus/php-image#multiline-text-box-with-auto-wrap-and-auto-font-scale-to-fit-bounds or https://github.com/kus/php-image/blob/master/test/text.php
