### ISSUE TITLE
Resize a image before overlay draw

### ISSUE THREAD

**Issue by lincolnlemos** [kus/php-image#4]
Its possible? I dont found how...Look my code:

$avatar = new PHPImage('url_from_image');
$avatar->resize(100, 100, true, true);

$image = new PHPImage();
$image->setDimensionsFromImage($bg);
$image->draw($bg);
$image->draw($avatar,50,69);

**Comment by Svish** [comment]
Needed the same, and wasn't possible as far as I could figure, but seems to be possible with the small addition I made in #7 :smile:

**Comment by kus** [comment]
Hi @lincolnlemos yes it is possible after @Svish patch he made (Thanks @Svish)

I made an example if you are still interested in it https://github.com/kus/php-image/blob/master/test/multiple-instances.php
